## .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: P${{ matrix.php-version }} L${{ matrix.laravel-version }} ${{ matrix.dependency-stability }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4']
        laravel-version: ['11.*', '12.*']
        dependency-stability: ['prefer-lowest', 'prefer-dist']

        include:
          - php-version: '8.4'
            laravel-version: '12.*'
            dependency-stability: 'phpstan'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, gd, intl, simplexml
          coverage: none

      - name: Install Dependencies (Default Jobs)
        # Runs for 'prefer-lowest' and 'prefer-dist'
        if: matrix.dependency-stability != 'phpstan'
        run: |
          composer update --${{ matrix.dependency-stability }} --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Dependencies (PHPStan Job)
        # Runs a standard install for the dedicated PHPStan check
        if: matrix.dependency-stability == 'phpstan'
        run: |
          composer update --prefer-dist --no-interaction --optimize-autoloader

      - name: Run Pest Tests
        if: matrix.dependency-stability != 'phpstan'
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: |
          vendor/bin/pest