## .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: P${{ matrix.php-version }} L${{ matrix.laravel-version }} ${{ matrix.dependency-stability }}

    runs-on: ubuntu-latest

    strategy:
      # If one combination fails, continue testing others for full report
      fail-fast: false
      matrix:
        # Define the PHP versions to test against
        php-version: ['8.3', '8.4']

        # Define the Laravel versions to test against
        laravel-version: ['11.*', '12.*']

        # Test both the latest available dependencies and the minimum required ones
        dependency-stability: ['prefer-lowest', 'prefer-dist']

        include:
          # --- Dedicated PHPStan Job (Runs Once on the latest stable stack) ---
          - php-version: '8.4'
            laravel-version: '12.*'
            dependency-stability: 'phpstan'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, gd, intl, simplexml
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer update --${{ matrix.dependency-stability }} --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Pest Tests
        if: matrix.dependency-stability != 'phpstan'
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: |
          vendor/bin/pest